apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer-spy
  namespace: kafka
spec:
  containers:
  - name: spy
    image: quay.io/strimzi/kafka:0.41.0-kafka-3.8.0
    # This is the command to run the consumer
    command: ["bin/kafka-console-consumer.sh"]
    # These are the arguments for the command
    args: [
      "--bootstrap-server", "my-cluster-kafka-bootstrap.kafka.svc:9092",
      "--topic", "bid-responses",
      "--from-beginning",
      "--property", "print.key=true",
      "--property", "key.separator= | "
    ]
    # These two lines are the equivalent of "-it"
    # They keep the pod alive and wait for us to attach.
    stdin: true
    tty: true
  # We want to run this once, not restart it if it fails
  restartPolicy: Never

# Did this separately because of timeout issues happening with direct command:-
# minikube kubectl -- run kafka-consumer-spy -n kafka --image=strimzi/kafka:0.41.0-kafka-3.8.0 --rm -it -- bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap.kafka.svc:9092 --topic bid-responses --from-beginning --property print.key=true --property key.separator=" | "
# The above command was timing out before the pod could be created because it was taking too long to download the image.